### ISSUE TITLE
[BUG] Container Deployment Fails on Container Creation

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/LibreTranslate#2]
### Description

When creating a container from the default (only) tag `latest`, the container fails with the exception noted below.

### Steps to Reproduce

- pull the latest container from `ghcr.io/neongeckocom/libretranslate:latest`
- start the container

### Other Notes

```
Updating language models
Found 60 models
Downloading Arabic → English (1.0) ...
Cannot update models (normal if you're offline): name 'url' is not defined
Traceback (most recent call last):
  File "/usr/local/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/app/main.py", line 123, in main
    app, translate_request = create_app(args)
  File "/usr/local/lib/python3.8/site-packages/app/app.py", line 140, in create_app
    frontend_argos_language_source = languages[0]
IndexError: list index out of range
```

**Comment by NeonBohdan** [comment]
@NeonDaniel please reopen if it hasn't fixed problem for you(works for me)
